### ISSUE TITLE
Reaching out

### ISSUE THREAD

**Issue by petit-perou** [pmonks/clj-spdx#45]
## Reaching out

Hello,

I hope this message finds you well.

I am a clojure dev and I am working on a project to build a platform to audit software. We are thinking of choosing SPDX-v3 (instead of cyclone DX) as SBOM format.

I'm following the development of this library an plan to maybe use it within some *analayzer* module, I'm mostly focused into reproducing the SPDX graph within some database at the moment.

Anyway, I noticed that you changed license for this project, which is a business case for my project so I'm taking my chance to reach out with some questions about this project:

- why changing license?
- did you choose spdx because to license expressions stuff matched your requirements?
- would you like to talk a little bit about sboms with me?

I'm on clojurians (Antoine Zimmermann) and github :)

Regards,

Antoine

**Comment by pmonks** [comment]
Hi Antoine,

I'm not on the Clojurians Slack, but am on [the Clojure Discord](https://discord.gg/discljord), if you'd like to chat there.  I'm more than happy to discuss your plans (incl. your questions), but would rather not do it here as it pollutes the GitHub issues for the project.

Hope to chat soon!
